// AUTO-GENERATED by scripts/download_brand_icons.dart
// DO NOT EDIT MANUALLY
import 'package:flutter/material.dart';

class BrandIcons {
  static const aiBrands = <String, IconInfo>{
    'OpenAI': IconInfo('assets/icons/openai.svg', Color(0xFF00A67E)),
    'ChatGPT': IconInfo('assets/icons/chatgpt.svg', Color(0xFF00A67E)),
    'Anthropic': IconInfo('assets/icons/anthropic.svg', Color(0xFFD97757)),
    'Claude': IconInfo('assets/icons/claude.svg', Color(0xFFD97757)),
    'DeepSeek': IconInfo('assets/icons/deepseek.svg', Color(0xFF4D6BFE)),
    'Gemini': IconInfo('assets/icons/gemini.svg', Color(0xFF4285F4)),
    '通义千问': IconInfo('assets/icons/qwen.svg', Color(0xFFFF6A00)),
    '智谱': IconInfo('assets/icons/zhipu.svg', Color(0xFF2563EB)),
    'GLM': IconInfo('assets/icons/glm.svg', Color(0xFF2563EB)),
    'MiniMax': IconInfo('assets/icons/minimax.svg', Color(0xFF7C3AED)),
    'Kimi': IconInfo('assets/icons/kimi.svg', Color(0xFF6C5CE7)),
    '月之暗面': IconInfo('assets/icons/moonshot.svg', Color(0xFF6C5CE7)),
    '文心一言': IconInfo('assets/icons/ernie.svg', Color(0xFF2468E6)),
    '混元': IconInfo('assets/icons/hunyuan.svg', Color(0xFF00C3B1)),
    '讯飞星火': IconInfo('assets/icons/spark.svg', Color(0xFF2B65F5)),
    'SenseNove': IconInfo('assets/icons/sensenova.svg', Color(0xFF1E40AF)),
    '商汤': IconInfo('assets/icons/sensetime.svg', Color(0xFF1E40AF)),
  };
  static const bankBrands = <String, IconInfo>{
    '工商银行': IconInfo('assets/icons/bank_icbc.svg', Color(0xFFCC0000)),
    '农业银行': IconInfo('assets/icons/bank_abc.svg', Color(0xFF009B72)),
    '中国银行': IconInfo('assets/icons/bank_boc.svg', Color(0xFFCE0000)),
    '建设银行': IconInfo('assets/icons/bank_ccb.svg', Color(0xFF0066CC)),
    '交通银行': IconInfo('assets/icons/bank_bocom.svg', Color(0xFF005BAB)),
    '邮储银行': IconInfo('assets/icons/bank_psbc.svg', Color(0xFF007A3D)),
    '招商银行': IconInfo('assets/icons/bank_cmb.svg', Color(0xFFCE0000)),
    '浦发银行': IconInfo('assets/icons/bank_spd.svg', Color(0xFF003399)),
  };
  static const idBrands = <String, IconInfo>{
    '身份证': IconInfo('assets/icons/id_身份证.svg', Color(0xFF2563EB)),
    '护照': IconInfo('assets/icons/id_护照.svg', Color(0xFF059669)),
    '驾照': IconInfo('assets/icons/id_驾照.svg', Color(0xFFD97706)),
    '社保卡': IconInfo('assets/icons/id_社保卡.svg', Color(0xFFDC2626)),
    '户口本': IconInfo('assets/icons/id_户口本.svg', Color(0xFF7C3AED)),
  };

  static IconInfo? lookup(String? name) {
    if (name == null || name.isEmpty) return null;
    return aiBrands[name] ?? bankBrands[name] ?? idBrands[name];
  }
}

class IconInfo {
  final String assetPath;
  final Color color;
  const IconInfo(this.assetPath, this.color);
}
